-- NaZerak account schema
-- Run this once in Supabase SQL Editor.
--
-- Security model:
-- 1) Discord authentication is handled by Supabase Auth.
-- 2) Users can only read/write their own profile row.
-- 3) Media partner applications are a future moderation foundation; the public
--    site does not accept submissions until a review workflow exists.
-- 4) No browser client receives a service_role key.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  minecraft_username text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_minecraft_username_format
    check (
      minecraft_username is null
      or minecraft_username ~ '^[A-Za-z0-9_]{3,16}$'
    )
);

create table if not exists public.media_applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  channel_url text not null,
  message text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  constraint media_applications_status
    check (status in ('pending', 'approved', 'rejected')),
  constraint media_applications_channel_url_length
    check (char_length(channel_url) between 8 and 500),
  constraint media_applications_message_length
    check (char_length(message) between 10 and 2000),
  constraint media_applications_channel_url_scheme
    check (channel_url ~* '^https?://')
);

create unique index if not exists media_applications_one_pending_per_user
  on public.media_applications (user_id)
  where status = 'pending';


alter table public.profiles enable row level security;
alter table public.media_applications enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles
  for select
  to authenticated
  using ((select auth.uid()) = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles
  for insert
  to authenticated
  with check ((select auth.uid()) = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles
  for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists "media_applications_select_own" on public.media_applications;
create policy "media_applications_select_own"
  on public.media_applications
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "media_applications_insert_own" on public.media_applications;
create policy "media_applications_insert_own"
  on public.media_applications
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

-- Browser privileges: deny anonymous access, then restore only what the UI uses.
revoke all on table public.profiles, public.media_applications from anon;

revoke insert, update, delete, references, trigger, truncate
  on table public.profiles
  from authenticated;
revoke all on table public.media_applications
  from authenticated;

revoke all on sequence public.media_applications_id_seq from anon;

grant select on public.profiles to authenticated;
-- Media applications intentionally have no browser grants yet.
-- Add narrow SELECT/INSERT grants only when a real moderation workflow exists.

grant insert (id, minecraft_username)
  on table public.profiles to authenticated;
grant update (minecraft_username, updated_at)
  on table public.profiles to authenticated;

grant usage, select
  on sequence public.media_applications_id_seq
  to authenticated;

comment on table public.profiles is 'NaZerak user profile, keyed to Supabase Auth user id.';
comment on table public.media_applications is 'Future NaZerak media partner application queue; browser intake is disabled until moderation exists.';
