-- NaZerak account schema
-- Run this once in Supabase SQL Editor.
--
-- Security model:
-- 1) Discord authentication is handled by Supabase Auth.
-- 2) Users can only read/write their own profile row.
-- 3) Media partner applications are a future moderation foundation; the public
--    site does not accept submissions until a review workflow exists.
-- 4) No browser client receives a service_role key.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  minecraft_username text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_minecraft_username_format
    check (
      minecraft_username is null
      or minecraft_username ~ '^[A-Za-z0-9_]{3,16}$'
    )
);

create table if not exists public.media_applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  channel_url text not null,
  message text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  constraint media_applications_status
    check (status in ('pending', 'approved', 'rejected')),
  constraint media_applications_channel_url_length
    check (char_length(channel_url) between 8 and 500),
  constraint media_applications_message_length
    check (char_length(message) between 10 and 2000),
  constraint media_applications_channel_url_scheme
    check (channel_url ~* '^https?://')
);

create unique index if not exists media_applications_one_pending_per_user
  on public.media_applications (user_id)
  where status = 'pending';


alter table public.profiles enable row level security;
alter table public.media_applications enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles
  for select
  to authenticated
  using ((select auth.uid()) = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles
  for insert
  to authenticated
  with check ((select auth.uid()) = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles
  for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists "media_applications_select_own" on public.media_applications;
create policy "media_applications_select_own"
  on public.media_applications
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "media_applications_insert_own" on public.media_applications;
create policy "media_applications_insert_own"
  on public.media_applications
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

-- Browser privileges: deny anonymous access, then restore only what the UI uses.
revoke all on table public.profiles, public.media_applications from anon;

revoke insert, update, delete, references, trigger, truncate
  on table public.profiles
  from authenticated;
revoke all on table public.media_applications
  from authenticated;

revoke all on sequence public.media_applications_id_seq from anon;

grant select on public.profiles to authenticated;
-- Media applications intentionally have no browser grants yet.
-- Add narrow SELECT/INSERT grants only when a real moderation workflow exists.

grant insert (id, minecraft_username)
  on table public.profiles to authenticated;
grant update (minecraft_username, updated_at)
  on table public.profiles to authenticated;

grant usage, select
  on sequence public.media_applications_id_seq
  to authenticated;

comment on table public.profiles is 'NaZerak user profile, keyed to Supabase Auth user id.';
comment on table public.media_applications is 'Future NaZerak media partner application queue; browser intake is disabled until moderation exists.';


-- Forum foundation
create table if not exists public.forum_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  constraint forum_categories_slug_format check (slug ~ '^[a-z0-9-]{2,64}$'),
  constraint forum_categories_name_length check (char_length(name) between 2 and 80),
  constraint forum_categories_description_length check (char_length(description) <= 500)
);

create table if not exists public.forum_authors (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  avatar_url text,
  updated_at timestamptz not null default now()
);

create table if not exists public.forum_topics (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.forum_categories(id) on delete restrict,
  author_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text not null,
  is_pinned boolean not null default false,
  is_locked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_post_at timestamptz not null default now(),
  constraint forum_topics_title_length check (char_length(btrim(title)) between 3 and 120),
  constraint forum_topics_body_length check (char_length(btrim(body)) between 1 and 12000)
);

create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.forum_topics(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint forum_posts_body_length check (char_length(btrim(body)) between 1 and 12000)
);

alter table public.forum_categories enable row level security;
alter table public.forum_authors enable row level security;
alter table public.forum_topics enable row level security;
alter table public.forum_posts enable row level security;

drop policy if exists "forum_categories_public_read" on public.forum_categories;
create policy "forum_categories_public_read" on public.forum_categories for select to anon, authenticated using (true);
drop policy if exists "forum_authors_public_read" on public.forum_authors;
create policy "forum_authors_public_read" on public.forum_authors for select to anon, authenticated using (true);
drop policy if exists "forum_authors_insert_own" on public.forum_authors;
create policy "forum_authors_insert_own" on public.forum_authors for insert to authenticated with check ((select auth.uid()) = id);
drop policy if exists "forum_authors_update_own" on public.forum_authors;
create policy "forum_authors_update_own" on public.forum_authors for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

drop policy if exists "forum_topics_public_read" on public.forum_topics;
create policy "forum_topics_public_read" on public.forum_topics for select to anon, authenticated using (true);
drop policy if exists "forum_topics_insert_own" on public.forum_topics;
create policy "forum_topics_insert_own" on public.forum_topics for insert to authenticated with check ((select auth.uid()) = author_id);
drop policy if exists "forum_topics_update_own" on public.forum_topics;
create policy "forum_topics_update_own" on public.forum_topics for update to authenticated using ((select auth.uid()) = author_id) with check ((select auth.uid()) = author_id);
drop policy if exists "forum_topics_delete_own" on public.forum_topics;
create policy "forum_topics_delete_own" on public.forum_topics for delete to authenticated using ((select auth.uid()) = author_id);

drop policy if exists "forum_posts_public_read" on public.forum_posts;
create policy "forum_posts_public_read" on public.forum_posts for select to anon, authenticated using (true);
drop policy if exists "forum_posts_insert_own" on public.forum_posts;
create policy "forum_posts_insert_own" on public.forum_posts for insert to authenticated with check ((select auth.uid()) = author_id);
drop policy if exists "forum_posts_update_own" on public.forum_posts;
create policy "forum_posts_update_own" on public.forum_posts for update to authenticated using ((select auth.uid()) = author_id) with check ((select auth.uid()) = author_id);
drop policy if exists "forum_posts_delete_own" on public.forum_posts;
create policy "forum_posts_delete_own" on public.forum_posts for delete to authenticated using ((select auth.uid()) = author_id);

revoke all on table public.forum_categories, public.forum_authors, public.forum_topics, public.forum_posts from anon, authenticated;
grant select on public.forum_categories, public.forum_authors, public.forum_topics, public.forum_posts to anon, authenticated;
grant insert (category_id, author_id, title, body) on public.forum_topics to authenticated;
grant update (title, body, updated_at) on public.forum_topics to authenticated;
grant delete on public.forum_topics to authenticated;
grant insert (topic_id, author_id, body) on public.forum_posts to authenticated;
grant update (body, updated_at) on public.forum_posts to authenticated;
grant delete on public.forum_posts to authenticated;
grant insert (id, display_name, avatar_url, updated_at, last_seen_at) on public.forum_authors to authenticated;
grant update (display_name, avatar_url, updated_at, last_seen_at) on public.forum_authors to authenticated;


-- Forum identity, roles and public profiles.
create table if not exists public.forum_roles (
  slug text primary key,
  name text not null,
  short_name text not null,
  color text not null,
  badge text not null default '',
  description text not null default '',
  priority integer not null default 0,
  permissions text[] not null default '{}'
);

create table if not exists public.forum_user_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role_slug text not null references public.forum_roles(slug) on delete restrict,
  assigned_at timestamptz not null default now(),
  assigned_by uuid references auth.users(id) on delete set null,
  primary key (user_id, role_slug)
);

alter table public.forum_authors
  add column if not exists public_id uuid not null default gen_random_uuid(),
  add column if not exists bio text not null default '',
  add column if not exists minecraft_username text,
  add column if not exists joined_at timestamptz not null default now(),
  add column if not exists last_seen_at timestamptz,
  add column if not exists role_slugs jsonb not null default '[]'::jsonb,
  add column if not exists primary_role_slug text not null default 'player',
  add column if not exists primary_role_name text not null default 'Игрок',
  add column if not exists primary_role_color text not null default '#a9adb7',
  add column if not exists primary_role_badge text not null default '•';

alter table public.forum_topics
  add column if not exists slug text,
  add column if not exists views_count integer not null default 0,
  add column if not exists prefix text not null default '',
  add column if not exists is_archived boolean not null default false,
  add column if not exists solution_state text not null default 'none';

alter table public.forum_posts
  add column if not exists is_hidden boolean not null default false,
  add column if not exists edited_at timestamptz;

-- The public forum identity is always keyed by the Supabase Auth user.
-- Discord OAuth creates/owns that Auth account; no Discord password is stored here.


-- Final forum structure overlay.
alter table public.forum_categories
  add column if not exists area_slug text not null default 'rp';

alter table public.forum_categories
  drop constraint if exists forum_categories_area_slug_check;

alter table public.forum_categories
  add constraint forum_categories_area_slug_check
  check (area_slug in ('rp','administration'));

create index if not exists forum_categories_area_sort_idx
  on public.forum_categories(area_slug, sort_order, id);

-- Privileged Discord role bindings live outside exposed schemas.
create table if not exists private.forum_discord_role_bindings (
  discord_user_id text primary key,
  role_slug text not null references public.forum_roles(slug) on delete restrict,
  assigned_at timestamptz not null default now()
);

-- Real forum content is created manually; there is no starter-topic block here.


-- Forum category publication mode: open, official, or restricted.
alter table public.forum_categories
  add column if not exists posting_mode text not null default 'open';

-- Official publication is protected by the database permission layer.


-- Forum node tree
-- forum_categories is a hierarchical node table:
-- node_type=category is a non-posting container;
-- node_type=forum is a topic-bearing child node.
-- route_slug is the stable public forum slug used by forum-category.html.
-- parent_id references the immediate parent category.


-- Runtime forum integrity: keep topic activity timestamps current.
create or replace function private.touch_forum_topic_last_post()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_topic_id bigint;
  v_last_post_at timestamptz;
begin
  if tg_op = 'DELETE' then
    v_topic_id := old.topic_id;
  else
    v_topic_id := new.topic_id;
  end if;

  select greatest(
    t.created_at,
    coalesce(max(p.created_at) filter (where not p.is_hidden), t.created_at)
  )
  into v_last_post_at
  from public.forum_topics t
  left join public.forum_posts p on p.topic_id = t.id
  where t.id = v_topic_id
  group by t.id, t.created_at;

  update public.forum_topics
  set last_post_at = v_last_post_at,
      updated_at = greatest(updated_at, coalesce(v_last_post_at, updated_at))
  where id = v_topic_id;

  if tg_op = 'UPDATE' and old.topic_id is distinct from new.topic_id then
    update public.forum_topics t
    set last_post_at = greatest(
      t.created_at,
      coalesce(
        (select max(p.created_at) from public.forum_posts p where p.topic_id = t.id and not p.is_hidden),
        t.created_at
      )
    )
    where t.id = old.topic_id;
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists forum_topic_last_post_touch on public.forum_posts;
create trigger forum_topic_last_post_touch
after insert or update or delete on public.forum_posts
for each row execute function private.touch_forum_topic_last_post();

revoke all on function private.touch_forum_topic_last_post() from public, anon, authenticated;
