(() => {
"use strict";
const state={client:null,users:[],q:""};
const qs=(s,r=document)=>r.querySelector(s),safeUrl=v=>{try{const u=new URL(String(v||""));return /^https?:$/.test(u.protocol)?u.href:"";}catch{return"";}},esc=v=>String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const wait=async()=>{for(let i=0;i<100;i++){if(window.NaZerakAuth?.client)return window.NaZerakAuth.client;await new Promise(r=>setTimeout(r,100));}return null;};
const withTimeout=async(promise,ms)=>{let timer;try{return await Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error("Запрос участников превысил 8 секунд.")),ms);})]);}finally{clearTimeout(timer);}};
const render=()=>{const root=qs("[data-members-list]"),empty=qs("[data-members-empty]");const users=state.users.filter(u=>{const q=state.q.trim().toLowerCase();return !q||[u.display_name,u.minecraft_username,u.primary_role_name].join(" ").toLowerCase().includes(q);});qs("[data-members-count]").textContent=users.length+" "+(users.length===1?"участник":users.length<5?"участника":"участников");if(!users.length){root.innerHTML="";root.hidden=true;empty.hidden=false;return;}root.hidden=false;empty.hidden=true;root.innerHTML=users.map(u=>{const a=safeUrl(u.avatar_url),media=a?'<img src="'+esc(a)+'" alt="">':esc((u.display_name||"N").slice(0,1).toUpperCase());const role=esc(u.primary_role_slug||"player");return '<a class="forum-member-card forum-role--'+role+'" href="/user/'+encodeURIComponent(u.public_id)+'" data-forum-user="'+esc(u.public_id)+'"><span class="forum-avatar">'+media+'</span><span class="forum-member-card__body"><strong>'+esc(u.display_name)+'</strong><small>'+esc(u.primary_role_badge||"•")+" "+esc(u.primary_role_name||"Игрок")+'</small><span>'+Number(u.post_count||0)+" сообщений · "+Number(u.topic_count||0)+" тем"+(u.minecraft_username?" · "+esc(u.minecraft_username):"")+'</span></span></a>';}).join("");};
const init=async()=>{const error=qs("[data-members-message]");state.client=await wait();if(!state.client){if(error){error.textContent="Не удалось подключиться к данным форума. Обнови страницу и попробуй снова.";error.hidden=false;}return;}try{const r=await withTimeout(state.client.from("forum_author_directory").select("public_id,display_name,avatar_url,bio,minecraft_username,joined_at,last_seen_at,topic_count,post_count,role_slugs,primary_role_slug,primary_role_name,primary_role_color,primary_role_badge").order("display_name",{ascending:true}).limit(200),8000);if(r.error)throw new Error(r.error.message||"Не удалось загрузить участников.");state.users=r.data||[];render();if(error)error.hidden=true;}catch(e){if(error){error.textContent=e instanceof Error?e.message:"Не удалось загрузить участников.";error.hidden=false;}return;}qs("#members-search")?.addEventListener("input",e=>{state.q=e.target.value||"";qs("[data-members-clear]").hidden=!state.q;render();});qs("[data-members-clear]")?.addEventListener("click",()=>{state.q="";qs("#members-search").value="";qs("[data-members-clear]").hidden=true;render();});};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>void init(),{once:true});else void init();
})();