(() => {
  'use strict';
  const state = { client: null, user: null, results: [] };
  const qs = (s, r = document) => r.querySelector(s);
  const qsa = (s, r = document) => Array.from(r.querySelectorAll(s));
  const escapeHtml = (v) => String(v == null ? '' : v).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]));
  const safeUrl = (v) => { try { const u = new URL(String(v || '')); return /^https?:$/.test(u.protocol) ? u.href : ''; } catch { return ''; } };
  const msg = (m, k = 'info') => { const n = qs('[data-search-message]'); if (!n) return; n.textContent = m; n.dataset.kind = k; n.hidden = !m; };
  const relative = (v) => { const d = new Date(v), diff = Date.now() - d.getTime(); if (Number.isNaN(d.getTime())) return '—'; const m = Math.max(0, Math.floor(diff / 60000)); if (m < 1) return 'только что'; if (m < 60) return m + 'м назад'; if (m < 1440) return Math.floor(m / 60) + 'ч назад'; return Math.floor(m / 1440) + 'д назад'; };
  const formatResults = () => { const root = qs('[data-search-results]'); const empty = qs('[data-search-empty]'); const count = qs('[data-search-count]'); if (!root || !empty) return; root.innerHTML = state.results.map(t => `<article class="forum-topic-row" data-topic-id="${escapeHtml(t.id)}"><div class="forum-topic-row__mark">›</div><div class="forum-topic-row__copy"><div class="forum-topic-row__tags"><span>${escapeHtml(t.category_name || 'Форум')}</span></div><a href="./topic.html?id=${encodeURIComponent(t.id)}" style="color:inherit;text-decoration:none"><h3>${escapeHtml(t.title)}</h3></a><p>${escapeHtml((t.body || '').slice(0, 120))}${(t.body || '').length > 120 ? '...' : ''}</p><div class="forum-topic-row__author"><div class="forum-avatar forum-avatar--small"><span>${escapeHtml((t.author_name || 'N').slice(0, 1).toUpperCase())}</span></div><span>${escapeHtml(t.author_name || 'Игрок')}</span></div></div><div class="forum-topic-row__replies"><strong>${Number(t.reply_count || 0)}</strong><span>ответов</span></div></article>`).join(''); const n = state.results.length; count.textContent = n === 1 ? '1 результат' : n + ' результатов'; empty.hidden = n > 0; };
  const search = async () => { const input = qs('[data-search-input]'); if (!input || !input.value.trim()) { state.results = []; formatResults(); return; } if (!state.client) return; const q = input.value.trim().slice(0, 100); const r = await state.client.from('forum_topic_list').select('id,title,body,category_name,author_name,reply_count').ilike('title', `%${q}%`).order('created_at', { ascending: false }).limit(50); if (r.error) { msg('Ошибка поиска', 'error'); console.error(r.error); return; } state.results = r.data || []; formatResults(); };
  const debounce = (fn, ms) => { let timer; return (...args) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), ms); }; };
  const init = async () => { state.client = await (async () => { for (let i = 0; i < 100; i++) { if (window.NaZerakAuth?.client) return window.NaZerakAuth.client; await new Promise(r => setTimeout(r, 100)); } return null; })(); if (!state.client) { msg('Не удалось подключиться к форуму', 'error'); return; } const input = qs('[data-search-input]'); const clear = qs('[data-search-clear]'); if (input) { const doSearch = debounce(search, 300); input.addEventListener('input', (e) => { if (e.target.value.trim()) { clear.hidden = false; doSearch(); } else { clear.hidden = true; state.results = []; formatResults(); } }); } if (clear) { clear.addEventListener('click', () => { input.value = ''; clear.hidden = true; state.results = []; formatResults(); input.focus(); }); } };
  if (document.readyState === 'loading') { document.addEventListener('DOMContentLoaded', () => void init(), { once: true }); } else { void init(); }
})();
