(() => {
"use strict";
const state={client:null,topics:[],q:""};
const qs=(s,r=document)=>r.querySelector(s),safeUrl=v=>{try{const u=new URL(String(v||""));return /^https?:$/.test(u.protocol)?u.href:"";}catch{return"";}},esc=v=>String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const wait=async()=>{for(let i=0;i<100;i++){if(window.NaZerakAuth?.client)return window.NaZerakAuth.client;await new Promise(r=>setTimeout(r,100));}return null;};
const withTimeout=async(promise,ms)=>{let timer;try{return await Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error("Поиск форума превысил 8 секунд.")),ms);})]);}finally{clearTimeout(timer);}};
const render=()=>{const root=qs("[data-search-results]"),empty=qs("[data-search-empty]"),q=state.q.trim().toLowerCase();const items=!q?[]:state.topics.filter(t=>[t.title,t.body,t.category_name,t.author_name].join(" ").toLowerCase().includes(q));qs("[data-search-title]").textContent=q?'Результаты для «'+state.q.trim()+'»':"Результаты";qs("[data-search-count]").textContent=items.length+" "+(items.length===1?"тема":items.length<5?"темы":"тем");if(!items.length){root.hidden=true;empty.hidden=false;return;}root.hidden=false;empty.hidden=true;root.innerHTML=items.map(t=>{const a=safeUrl(t.author_avatar_url),av=a?'<img src="'+esc(a)+'" alt="">':esc((t.author_name||"N").slice(0,1).toUpperCase());return '<article class="forum-topic-row"><a class="forum-topic-row__open" href="./topic.html?id='+encodeURIComponent(t.id)+'"><div class="forum-topic-row__mark">'+(t.is_pinned?window.NaZerakForumUI.icon("pin",18):window.NaZerakForumUI.icon("chat",18))+'</div><div class="forum-topic-row__copy"><div class="forum-topic-row__tags"><span>'+esc(t.category_name)+'</span>'+ (t.prefix?'<span class="forum-topic-row__prefix">'+esc(t.prefix)+'</span>':"")+'</div><h3>'+esc(t.title)+'</h3><p>'+esc(String(t.body||"").replace(/\s+/g," ").slice(0,180))+'</p></div></a><div class="forum-topic-row__footer"><a class="forum-user-link forum-role--'+esc(t.primary_role_slug||"player")+'" data-forum-user="'+esc(t.author_public_id||"")+'" href="./forum-user.html?id='+encodeURIComponent(t.author_public_id||"")+'"><span class="forum-avatar forum-avatar--small">'+av+'</span><span>'+esc(t.author_name||"Игрок NaZerak")+'</span><span class="forum-user-link__role">'+esc(t.primary_role_name||"Игрок")+'</span></a><div class="forum-topic-row__activity"><strong>'+Number(t.reply_count||0)+'</strong><span>ответов</span></div></div></article>';}).join("");};
const init=async()=>{const error=qs("[data-search-message]");state.client=await wait();if(!state.client){if(error){error.textContent="Не удалось подключиться к данным форума. Обнови страницу и попробуй снова.";error.hidden=false;}return;}try{const r=await withTimeout(state.client.from("forum_topic_list").select("id,title,body,category_name,author_public_id,author_name,author_avatar_url,primary_role_slug,primary_role_name,prefix,is_pinned,last_post_at,reply_count").order("last_post_at",{ascending:false}).limit(200),8000);if(r.error)throw new Error(r.error.message||"Не удалось загрузить темы.");state.topics=r.data||[];if(error)error.hidden=true;}catch(e){if(error){error.textContent=e instanceof Error?e.message:"Не удалось загрузить темы.";error.hidden=false;}return;}const form=qs("[data-forum-search-form]"),input=qs("#global-forum-search");const sync=()=>{const urlQ=new URLSearchParams(location.search).get("q")||"";state.q=input?.value||urlQ;render();if(input)input.value=state.q;const c=qs("[data-forum-search-clear]");if(c)c.hidden=!state.q;};form?.addEventListener("submit",e=>{e.preventDefault();state.q=input?.value||"";const url=new URL(location.href);if(state.q.trim())url.searchParams.set("q",state.q.trim());else url.searchParams.delete("q");history.replaceState({}, "", url);render();});qs("[data-forum-search-clear]")?.addEventListener("click",()=>{state.q="";input.value="";history.replaceState({}, "", location.pathname);render();});sync();};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>void init(),{once:true});else void init();
})();