(() => {
  'use strict';
  const state = { client: null, user: null, topic: null, posts: [] };
  const qs = (s, r = document) => r.querySelector(s);
  const escapeHtml = (v) => String(v == null ? '' : v).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]));
  const safeUrl = (v) => { try { const u = new URL(String(v || '')); return /^https?:$/.test(u.protocol) ? u.href : ''; } catch { return ''; } };
  const msg = (m, k = 'info') => { const n = qs('[data-topic-message]'); if (!n) return; n.textContent = m; n.dataset.kind = k; n.hidden = !m; };
  const formatDate = (v) => { const d = new Date(v); if (Number.isNaN(d.getTime())) return '—'; return new Intl.DateTimeFormat('ru-RU', { day: '2-digit', month: 'short', year: 'numeric' }).format(d); };
  const relative = (v) => { const d = new Date(v), diff = Date.now() - d.getTime(); if (Number.isNaN(d.getTime())) return '—'; const m = Math.max(0, Math.floor(diff / 60000)); if (m < 1) return 'только что'; if (m < 60) return m + 'м назад'; if (m < 1440) return Math.floor(m / 60) + 'ч назад'; return Math.floor(m / 1440) + 'д назад'; };
  const load = async () => { if (!state.client) return; const id = String(new URLSearchParams(location.search).get('id') || ''); if (!id) throw new Error('Тема не указана'); const r = await state.client.from('forum_topics').select('id,category_id,category_name,author_id,author_public_id,author_name,author_avatar_url,title,body,created_at,is_locked').eq('id', id).maybeSingle(); if (r.error) throw r.error; if (!r.data) throw new Error('Тема не найдена'); state.topic = r.data; qs('[data-topic-title]').textContent = state.topic.title; qs('[data-topic-author]').textContent = state.topic.author_name || 'Игрок'; qs('[data-topic-date]').textContent = formatDate(state.topic.created_at); qs('[data-topic-category-link]').href = `./forum-category.html?slug=${encodeURIComponent(state.topic.category_name)}`; qs('[data-topic-category-badge]').textContent = state.topic.category_name; const avatar = safeUrl(state.topic.author_avatar_url); if (avatar) { const img = qs('[data-topic-author-avatar]'); if (img) { img.src = avatar; img.hidden = false; } } else { qs('[data-topic-author-initial]').textContent = escapeHtml((state.topic.author_name || 'N').slice(0, 1).toUpperCase()); } const post = qs('[data-topic-posts]'); post.innerHTML = `<article class="topic-post"><div class="topic-post__author"><div class="forum-avatar">${avatar ? `<img src="${escapeHtml(avatar)}" alt="">` : escapeHtml((state.topic.author_name || 'N').slice(0, 1).toUpperCase())}</div><a href="./forum-user.html?id=${encodeURIComponent(state.topic.author_public_id)}" class="forum-role--player">${escapeHtml(state.topic.author_name || 'Игрок')}</a></div><div class="topic-post__body"><div class="topic-post__header"><strong class="topic-post__author-name">${escapeHtml(state.topic.author_name || 'Игрок')}</strong><span class="topic-post__date">${formatDate(state.topic.created_at)}</span></div><div class="topic-post__text">${escapeHtml(state.topic.body).replace(/\n/g, '<br>')}</div></div></article>`; const reply = qs('[data-topic-reply]'); const login = qs('[data-topic-login]'); if (state.user) { reply.hidden = false; login.hidden = true; } else { reply.hidden = true; login.hidden = false; } if (state.topic.is_locked) { const lock = qs('[data-topic-lock-note]'); if (lock) lock.textContent = 'Тема закрыта для ответов'; const btn = qs('[data-topic-reply-submit]'); if (btn) btn.disabled = true; } document.title = 'NaZerak — ' + state.topic.title; };
  const reply = async () => { if (!state.user || !state.topic) return; const input = qs('[data-topic-reply-input]'); if (!input || !input.value.trim()) { msg('Напиши сообщение', 'error'); return; } const btn = qs('[data-topic-reply-submit]'); if (btn) btn.disabled = true; const r = await state.client.from('forum_posts').insert({ topic_id: state.topic.id, author_id: state.user.id, body: input.value.trim() }).select('id').single(); if (btn) btn.disabled = false; if (r.error) { msg(r.error.message, 'error'); return; } input.value = ''; msg('Ответ добавлен!', 'success'); setTimeout(() => location.reload(), 1200); };
  const init = async () => { state.client = await (async () => { for (let i = 0; i < 100; i++) { if (window.NaZerakAuth?.client) return window.NaZerakAuth.client; await new Promise(r => setTimeout(r, 100)); } return null; })(); if (!state.client) { msg('Не удалось подключиться к форуму', 'error'); return; } if (window.NaZerakAuth?.user) state.user = window.NaZerakAuth.user; try { await load(); } catch (e) { msg(e.message, 'error'); } const btn = qs('[data-topic-reply-submit]'); if (btn) btn.addEventListener('click', reply); };
  if (document.readyState === 'loading') { document.addEventListener('DOMContentLoaded', () => void init(), { once: true }); } else { void init(); }
})();
