(() => {
  "use strict";
  const state={client:null,user:null,topic:null};
  const qs=(s,r=document)=>r.querySelector(s);
  const escapeHtml=(v)=>String(v==null?"":v).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c];});
  const safeUrl=(v)=>{try{const u=new URL(String(v||""));return /^https?:$/.test(u.protocol)?u.href:"";}catch{return"";}};
  const formatDateTime=(v)=>{const d=new Date(v);if(Number.isNaN(d.getTime()))return"—";return new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d);};
  const userName=(u)=>{const m=u&&u.user_metadata||{};return String(m.global_name||m.full_name||m.name||m.user_name||"Игрок NaZerak").trim().slice(0,64)||"Игрок NaZerak";};
  const userAvatar=(u)=>safeUrl(u&&u.user_metadata&&(u.user_metadata.avatar_url||u.user_metadata.picture));
  const showMessage=(m,k)=>{const n=qs("[data-topic-message]");if(!n)return;n.textContent=m;n.dataset.kind=k||"info";n.hidden=!m;};
  const waitForClient=async()=>{for(let i=0;i<100;i+=1){const c=window.NaZerakAuth&&window.NaZerakAuth.client;if(c)return c;await new Promise(function(r){window.setTimeout(r,100);});}return null;};
  const syncAuthor=async()=>{if(!state.client||!state.user)return;await state.client.from("forum_authors").upsert({id:state.user.id,display_name:userName(state.user),avatar_url:userAvatar(state.user)||null,updated_at:new Date().toISOString()},{onConflict:"id"});};
  const loadTopic=async()=>{const id=Number(new URLSearchParams(window.location.search).get("id"));if(!Number.isSafeInteger(id)||id<1)throw new Error("Некорректная тема форума.");const results=await Promise.all([state.client.from("forum_topics").select("id,category_id,author_id,title,body,is_pinned,is_locked,created_at,updated_at,last_post_at").eq("id",id).maybeSingle(),state.client.from("forum_posts").select("id,topic_id,author_id,body,created_at,updated_at").eq("topic_id",id).order("created_at",{ascending:true})]);if(results[0].error)throw new Error(results[0].error.message);if(!results[0].data)throw new Error("Тема не найдена или была удалена.");if(results[1].error)throw new Error(results[1].error.message);const ids=Array.from(new Set([results[0].data.author_id].concat((results[1].data||[]).map(function(p){return p.author_id;})))).filter(Boolean);const authors=ids.length?await state.client.from("forum_authors").select("id,display_name,avatar_url").in("id",ids):{data:[],error:null};const category=await state.client.from("forum_categories").select("id,name,slug").eq("id",results[0].data.category_id).maybeSingle();if(authors.error)throw new Error(authors.error.message);if(category.error)throw new Error(category.error.message);state.topic=results[0].data;renderTopic(results[0].data,category.data,Object.fromEntries((authors.data||[]).map(function(a){return[a.id,a];})),results[1].data||[]);};
  const renderTopic=(topic,category,authors,posts)=>{const author=authors[topic.author_id]||{display_name:"Игрок NaZerak",avatar_url:null},avatar=safeUrl(author.avatar_url);qs("[data-topic-category]").textContent=category&&category.name||"Форум";qs("[data-topic-category-badge]").textContent=category&&category.name||"Форум";qs("[data-topic-title]").textContent=topic.title;qs("[data-topic-date]").textContent=formatDateTime(topic.created_at);qs("[data-topic-author]").textContent=author.display_name;const img=qs("[data-topic-author-avatar]");img.hidden=!avatar;if(avatar){img.src=avatar;img.alt="";}qs("[data-topic-author-initial]").textContent=(author.display_name||"N").slice(0,1).toUpperCase();const items=[Object.assign({},topic,{_kind:"opening"})].concat((posts||[]).map(function(p){return Object.assign({},p,{_kind:"reply"});}));qs("[data-topic-posts]").innerHTML=items.map(function(item,index){const a=item._kind==="opening"?author:(authors[item.author_id]||{display_name:"Игрок NaZerak",avatar_url:null}),av=safeUrl(a.avatar_url),initial=escapeHtml((a.display_name||"N").slice(0,1).toUpperCase()),media=av?'<img src="'+escapeHtml(av)+'" alt="">':initial,label=index===0?"ПЕРВОЕ СООБЩЕНИЕ":"ОТВЕТ #"+index;return '<article class="topic-post'+(index===0?" topic-post--opener":"")+'"><aside class="topic-post__author"><div class="forum-avatar">'+media+'</div><strong>'+escapeHtml(a.display_name)+'</strong><span>'+ (index===0?"Автор темы":"Участник") +'</span></aside><div class="topic-post__body"><header><span>'+label+'</span><time datetime="'+escapeHtml(item.created_at)+'">'+formatDateTime(item.created_at)+'</time></header><div>'+escapeHtml(item.body).replace(/\n/g,"<br>")+'</div></div></article>';}).join("");qs("[data-topic-reply]").hidden=!state.user||topic.is_locked;qs("[data-topic-login]").hidden=!!state.user||topic.is_locked;if(topic.is_locked&&state.user)qs("[data-topic-lock-note]").textContent="Тема закрыта, новые ответы недоступны.";document.title="NaZerak — "+topic.title;};
  const reply=async()=>{const input=qs("[data-topic-reply-input]"),button=qs("[data-topic-reply-submit]"),body=String(input&&input.value||"").trim();if(!state.user||!state.client||!state.topic||button.disabled)return;if(!body){showMessage("Напиши текст ответа.","error");return;}button.disabled=true;button.querySelector("span").textContent="Публикуем…";showMessage("");await syncAuthor();const r=await state.client.from("forum_posts").insert({topic_id:state.topic.id,author_id:state.user.id,body:body});button.disabled=false;button.querySelector("span").textContent="Ответить";if(r.error){showMessage(r.error.message||"Не удалось опубликовать ответ.","error");return;}input.value="";await loadTopic();window.scrollTo({top:document.body.scrollHeight,behavior:"smooth"});};
  const init=async()=>{state.client=await waitForClient();if(!state.client){showMessage("Форум не смог подключиться к базе данных.","error");return;}const session=await state.client.auth.getSession();state.user=session.data&&session.data.session&&session.data.session.user||null;if(state.user)await syncAuthor();qs("[data-topic-reply-submit]")&&qs("[data-topic-reply-submit]").addEventListener("click",reply);try{await loadTopic();}catch(e){qs("[data-topic-head]").hidden=true;showMessage(e instanceof Error?e.message:"Не удалось загрузить тему.","error");}};
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",function(){void init();},{once:true});else void init();
})();