(() => {
  'use strict';
  const state = { client: null, profile: null };
  const qs = (s, r = document) => r.querySelector(s);
  const escapeHtml = (v) => String(v == null ? '' : v).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]));
  const safeUrl = (v) => { try { const u = new URL(String(v || '')); return /^https?:$/.test(u.protocol) ? u.href : ''; } catch { return ''; } };
  const msg = (m, k = 'info') => { const n = qs('[data-user-message]'); if (!n) return; n.textContent = m; n.dataset.kind = k; n.hidden = !m; };
  const formatDate = (v) => { const d = new Date(v); if (Number.isNaN(d.getTime())) return '—'; return new Intl.DateTimeFormat('ru-RU', { day: '2-digit', month: 'short', year: 'numeric' }).format(d); };
  const relative = (v) => { const d = new Date(v), diff = Date.now() - d.getTime(); if (Number.isNaN(d.getTime())) return '—'; const m = Math.max(0, Math.floor(diff / 60000)); if (m < 1) return 'только что'; if (m < 60) return m + 'м'; if (m < 1440) return Math.floor(m / 60) + 'ч'; return Math.floor(m / 1440) + 'д'; };
  const load = async () => { if (!state.client) return; const id = String(new URLSearchParams(location.search).get('id') || ''); if (!id) throw new Error('Пользователь не указан'); const r = await state.client.from('forum_author_directory').select('*').eq('public_id', id).maybeSingle(); if (r.error) throw r.error; if (!r.data) throw new Error('Пользователь не найден'); state.profile = r.data; qs('[data-user-profile]').hidden = false; qs('[data-user-content]').hidden = false; qs('[data-user-name]').textContent = state.profile.display_name || 'Игрок'; qs('[data-user-bio]').textContent = state.profile.bio || 'Участник форума NaZerak'; qs('[data-user-minecraft]').textContent = state.profile.minecraft_username || 'Не указан'; qs('[data-user-joined]').textContent = formatDate(state.profile.created_at); qs('[data-user-lastseen]').textContent = relative(state.profile.last_seen_at) + ' назад'; qs('[data-user-topic-count]').textContent = Number(state.profile.topic_count || 0); qs('[data-user-post-count]').textContent = Number(state.profile.post_count || 0); const avatar = safeUrl(state.profile.avatar_url); if (avatar) { const img = qs('[data-user-avatar]'); if (img) { img.src = avatar; img.hidden = false; } } else { qs('[data-user-initial]').textContent = escapeHtml((state.profile.display_name || 'N').slice(0, 1).toUpperCase()); } const roles = state.profile.role_slugs || []; qs('[data-user-roles]').innerHTML = roles.slice(0, 3).map(r => `<span class="forum-role forum-role--${escapeHtml(r.slug || 'player')}">● ${escapeHtml(r.name || 'Игрок')}</span>`).join(''); const topics = await state.client.from('forum_topic_list').select('id,title,category_name,created_at,reply_count').eq('author_public_id', id).order('created_at', { ascending: false }).limit(10); if (!topics.error && topics.data) { qs('[data-user-topics]').innerHTML = topics.data.map(t => `<article class="forum-topic-row"><div class="forum-topic-row__mark">›</div><div class="forum-topic-row__copy"><div class="forum-topic-row__tags"><span>${escapeHtml(t.category_name)}</span></div><a href="./topic.html?id=${encodeURIComponent(t.id)}" style="color:inherit;text-decoration:none"><h3>${escapeHtml(t.title)}</h3></a><div class="forum-topic-row__author"><time datetime="${escapeHtml(t.created_at)}">${formatDate(t.created_at)}</time></div></div><div class="forum-topic-row__replies"><strong>${Number(t.reply_count || 0)}</strong><span>ответов</span></div></article>`).join(''); } document.title = 'NaZerak — ' + (state.profile.display_name || 'Пользователь'); };
  const init = async () => { state.client = await (async () => { for (let i = 0; i < 100; i++) { if (window.NaZerakAuth?.client) return window.NaZerakAuth.client; await new Promise(r => setTimeout(r, 100)); } return null; })(); if (!state.client) { msg('Не удалось подключиться к форуму', 'error'); return; } try { await load(); } catch (e) { msg(e.message, 'error'); } };
  if (document.readyState === 'loading') { document.addEventListener('DOMContentLoaded', () => void init(), { once: true }); } else { void init(); }
})();
