begin;

create table if not exists public.forum_post_reactions (
  post_id bigint not null references public.forum_posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id),
  constraint forum_post_reactions_type_check check (reaction in ('like','helpful','love','wow','sad'))
);
create index if not exists forum_post_reactions_post_idx on public.forum_post_reactions(post_id, reaction);
alter table public.forum_post_reactions enable row level security;
drop policy if exists "forum_reactions_public_read" on public.forum_post_reactions;
create policy "forum_reactions_public_read" on public.forum_post_reactions for select to anon, authenticated using (true);
drop policy if exists "forum_reactions_insert_own" on public.forum_post_reactions;
create policy "forum_reactions_insert_own" on public.forum_post_reactions for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "forum_reactions_update_own" on public.forum_post_reactions;
create policy "forum_reactions_update_own" on public.forum_post_reactions for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "forum_reactions_delete_own" on public.forum_post_reactions;
create policy "forum_reactions_delete_own" on public.forum_post_reactions for delete to authenticated using ((select auth.uid()) = user_id);
revoke all on public.forum_post_reactions from anon, authenticated;
grant select on public.forum_post_reactions to anon, authenticated;
grant insert, update, delete on public.forum_post_reactions to authenticated;

create table if not exists public.forum_topic_bookmarks (
  topic_id bigint not null references public.forum_topics(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (topic_id, user_id)
);
alter table public.forum_topic_bookmarks enable row level security;
drop policy if exists "forum_bookmarks_own_read" on public.forum_topic_bookmarks;
create policy "forum_bookmarks_own_read" on public.forum_topic_bookmarks for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "forum_bookmarks_own_insert" on public.forum_topic_bookmarks;
create policy "forum_bookmarks_own_insert" on public.forum_topic_bookmarks for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "forum_bookmarks_own_delete" on public.forum_topic_bookmarks;
create policy "forum_bookmarks_own_delete" on public.forum_topic_bookmarks for delete to authenticated using ((select auth.uid()) = user_id);
revoke all on public.forum_topic_bookmarks from anon, authenticated;
grant select, insert, delete on public.forum_topic_bookmarks to authenticated;

create table if not exists public.forum_topic_watchers (
  topic_id bigint not null references public.forum_topics(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (topic_id, user_id)
);
alter table public.forum_topic_watchers enable row level security;
drop policy if exists "forum_watchers_own_read" on public.forum_topic_watchers;
create policy "forum_watchers_own_read" on public.forum_topic_watchers for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "forum_watchers_own_insert" on public.forum_topic_watchers;
create policy "forum_watchers_own_insert" on public.forum_topic_watchers for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "forum_watchers_own_delete" on public.forum_topic_watchers;
create policy "forum_watchers_own_delete" on public.forum_topic_watchers for delete to authenticated using ((select auth.uid()) = user_id);
revoke all on public.forum_topic_watchers from anon, authenticated;
grant select, insert, delete on public.forum_topic_watchers to authenticated;

create table if not exists public.forum_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  topic_id bigint references public.forum_topics(id) on delete cascade,
  post_id bigint references public.forum_posts(id) on delete cascade,
  reason text not null,
  status text not null default 'open',
  moderator_note text not null default '',
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references auth.users(id) on delete set null,
  constraint forum_reports_target_check check ((topic_id is not null and post_id is null) or (topic_id is null and post_id is not null)),
  constraint forum_reports_reason_length check (char_length(btrim(reason)) between 5 and 1000),
  constraint forum_reports_status_check check (status in ('open','reviewing','resolved','dismissed'))
);
create index if not exists forum_reports_status_created_idx on public.forum_reports(status, created_at desc);
create index if not exists forum_reports_reporter_idx on public.forum_reports(reporter_id, created_at desc);
alter table public.forum_reports enable row level security;
drop policy if exists "forum_reports_own_read" on public.forum_reports;
create policy "forum_reports_own_read" on public.forum_reports for select to authenticated using ((select auth.uid()) = reporter_id or (select private.has_forum_permission('moderate_forum')));
drop policy if exists "forum_reports_insert_own" on public.forum_reports;
create policy "forum_reports_insert_own" on public.forum_reports for insert to authenticated with check ((select auth.uid()) = reporter_id);
drop policy if exists "forum_reports_moderator_update" on public.forum_reports;
create policy "forum_reports_moderator_update" on public.forum_reports for update to authenticated using ((select private.has_forum_permission('moderate_forum'))) with check ((select private.has_forum_permission('moderate_forum')));
revoke all on public.forum_reports from anon, authenticated;
grant select, insert on public.forum_reports to authenticated;
grant update (status, moderator_note, resolved_at, resolved_by) on public.forum_reports to authenticated;
grant usage, select on sequence public.forum_reports_id_seq to authenticated;

create table if not exists public.forum_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  topic_id bigint references public.forum_topics(id) on delete cascade,
  post_id bigint references public.forum_posts(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null default '',
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  constraint forum_notifications_type_check check (type in ('reply','mention','reaction','moderation','system'))
);
create index if not exists forum_notifications_user_created_idx on public.forum_notifications(user_id, created_at desc);
create index if not exists forum_notifications_unread_idx on public.forum_notifications(user_id, is_read, created_at desc);
alter table public.forum_notifications enable row level security;
drop policy if exists "forum_notifications_own_read" on public.forum_notifications;
create policy "forum_notifications_own_read" on public.forum_notifications for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "forum_notifications_own_update" on public.forum_notifications;
create policy "forum_notifications_own_update" on public.forum_notifications for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
revoke all on public.forum_notifications from anon, authenticated;
grant select on public.forum_notifications to authenticated;
grant update (is_read) on public.forum_notifications to authenticated;
grant usage, select on sequence public.forum_notifications_id_seq to authenticated;

create or replace function private.forum_notify_topic_reply()
returns trigger language plpgsql security definer set search_path = pg_catalog, public
as $$
declare topic_author uuid; topic_title text;
begin
  select author_id, title into topic_author, topic_title from public.forum_topics where id = new.topic_id;
  if topic_author is not null and topic_author <> new.author_id then
    insert into public.forum_notifications(user_id,actor_id,topic_id,post_id,type,title,body)
    values(new.author_id, new.author_id, new.topic_id, new.id, 'reply', 'Новый ответ в вашей теме', topic_title);
  end if;
  insert into public.forum_notifications(user_id,actor_id,topic_id,post_id,type,title,body)
  select w.user_id,new.author_id,new.topic_id,new.id,'reply','Новый ответ в отслеживаемой теме',topic_title
  from public.forum_topic_watchers w
  where w.topic_id=new.topic_id and w.user_id <> new.author_id and w.user_id <> topic_author;
  return new;
end;
$$;
drop trigger if exists forum_notify_topic_reply on public.forum_posts;
create trigger forum_notify_topic_reply after insert on public.forum_posts for each row execute function private.forum_notify_topic_reply();
revoke all on function private.forum_notify_topic_reply() from public;

commit;