begin;

create table if not exists public.forum_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  constraint forum_categories_slug_format check (slug ~ '^[a-z0-9-]{2,64}$'),
  constraint forum_categories_name_length check (char_length(name) between 2 and 80),
  constraint forum_categories_description_length check (char_length(description) <= 500)
);

create table if not exists public.forum_authors (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  avatar_url text,
  updated_at timestamptz not null default now(),
  constraint forum_authors_display_name_length check (char_length(display_name) between 1 and 64),
  constraint forum_authors_avatar_url_scheme check (avatar_url is null or avatar_url ~* '^https?://')
);

create table if not exists public.forum_topics (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.forum_categories(id) on delete restrict,
  author_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text not null,
  is_pinned boolean not null default false,
  is_locked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_post_at timestamptz not null default now(),
  constraint forum_topics_title_length check (char_length(btrim(title)) between 3 and 120),
  constraint forum_topics_body_length check (char_length(btrim(body)) between 1 and 12000)
);

create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.forum_topics(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint forum_posts_body_length check (char_length(btrim(body)) between 1 and 12000)
);

create index if not exists forum_topics_category_updated_idx on public.forum_topics (category_id, last_post_at desc);
create index if not exists forum_topics_author_idx on public.forum_topics (author_id);
create index if not exists forum_posts_topic_created_idx on public.forum_posts (topic_id, created_at);
create index if not exists forum_posts_author_idx on public.forum_posts (author_id);

alter table public.forum_categories enable row level security;
alter table public.forum_authors enable row level security;
alter table public.forum_topics enable row level security;
alter table public.forum_posts enable row level security;

drop policy if exists "forum_categories_public_read" on public.forum_categories;
create policy "forum_categories_public_read" on public.forum_categories for select to anon, authenticated using (true);
drop policy if exists "forum_authors_public_read" on public.forum_authors;
create policy "forum_authors_public_read" on public.forum_authors for select to anon, authenticated using (true);
drop policy if exists "forum_authors_insert_own" on public.forum_authors;
create policy "forum_authors_insert_own" on public.forum_authors for insert to authenticated with check ((select auth.uid()) = id);
drop policy if exists "forum_authors_update_own" on public.forum_authors;
create policy "forum_authors_update_own" on public.forum_authors for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

drop policy if exists "forum_topics_public_read" on public.forum_topics;
create policy "forum_topics_public_read" on public.forum_topics for select to anon, authenticated using (true);
drop policy if exists "forum_topics_insert_own" on public.forum_topics;
create policy "forum_topics_insert_own" on public.forum_topics for insert to authenticated with check ((select auth.uid()) = author_id);
drop policy if exists "forum_topics_update_own" on public.forum_topics;
create policy "forum_topics_update_own" on public.forum_topics for update to authenticated using ((select auth.uid()) = author_id) with check ((select auth.uid()) = author_id);
drop policy if exists "forum_topics_delete_own" on public.forum_topics;
create policy "forum_topics_delete_own" on public.forum_topics for delete to authenticated using ((select auth.uid()) = author_id);

drop policy if exists "forum_posts_public_read" on public.forum_posts;
create policy "forum_posts_public_read" on public.forum_posts for select to anon, authenticated using (true);
drop policy if exists "forum_posts_insert_own" on public.forum_posts;
create policy "forum_posts_insert_own" on public.forum_posts for insert to authenticated with check ((select auth.uid()) = author_id);
drop policy if exists "forum_posts_update_own" on public.forum_posts;
create policy "forum_posts_update_own" on public.forum_posts for update to authenticated using ((select auth.uid()) = author_id) with check ((select auth.uid()) = author_id);
drop policy if exists "forum_posts_delete_own" on public.forum_posts;
create policy "forum_posts_delete_own" on public.forum_posts for delete to authenticated using ((select auth.uid()) = author_id);

revoke all on table public.forum_categories, public.forum_authors, public.forum_topics, public.forum_posts from anon, authenticated;
grant select on public.forum_categories to anon, authenticated;
grant select on public.forum_authors to anon, authenticated;
grant select on public.forum_topics to anon, authenticated;
grant insert (category_id, author_id, title, body) on public.forum_topics to authenticated;
grant update (title, body, updated_at) on public.forum_topics to authenticated;
grant delete on public.forum_topics to authenticated;
grant select on public.forum_posts to anon, authenticated;
grant insert (topic_id, author_id, body) on public.forum_posts to authenticated;
grant update (body, updated_at) on public.forum_posts to authenticated;
grant delete on public.forum_posts to authenticated;
grant usage, select on sequence public.forum_categories_id_seq to authenticated;
grant usage, select on sequence public.forum_topics_id_seq to authenticated;
grant usage, select on sequence public.forum_posts_id_seq to authenticated;

insert into public.forum_categories (slug, name, description, sort_order) values
('announcements','Новости и объявления','Официальные новости, изменения и важные сообщения проекта.',10),
('project','Проект','Обсуждение NaZerak, мира, правил и развития проекта.',20),
('minecraft','Minecraft','Строительство, игровой процесс, идеи и вопросы по Minecraft.',30),
('help','Помощь','Технические вопросы, подключение и помощь игрокам.',40),
('ideas','Идеи и предложения','Предложения по серверу, сайту и сообществу.',50)
on conflict (slug) do update set name=excluded.name, description=excluded.description, sort_order=excluded.sort_order;

comment on table public.forum_categories is 'Public NaZerak forum category registry.';
comment on table public.forum_authors is 'Public forum display identity owned by the corresponding authenticated user.';
comment on table public.forum_topics is 'NaZerak forum topics. Public read; authenticated users may manage their own topics.';
comment on table public.forum_posts is 'NaZerak forum replies. Public read; authenticated users may manage their own replies.';

commit;
